{ This is an autogenerated unit using gobject introspection (gir2pascal). Do not Edit. }
unit GdkPixbuf2;

{$MODE OBJFPC}{$H+}

{$PACKRECORDS C}
{$MODESWITCH DUPLICATELOCALS+}

interface
uses
  CTypes, GModule2, Gio2, GLib2, GObject2;

const
  GDK_PIXBUF_FEATURES_H = 1;
  GDK_PIXBUF_MAGIC_NUMBER = 1197763408;
  GDK_PIXBUF_MAJOR = 2;
  GDK_PIXBUF_MICRO = 12;
  GDK_PIXBUF_MINOR = 36;
  GDK_PIXBUF_VERSION = '2.36.12';
  GDK_PIXDATA_HEADER_LENGTH = 24;

type
  TGdkColorspace = DWord;
const
  { GdkColorspace }
  GDK_COLORSPACE_RGB: TGdkColorspace = 0;

type
  TGdkInterpType = DWord;
const
  { GdkInterpType }
  GDK_INTERP_NEAREST: TGdkInterpType = 0;
  GDK_INTERP_TILES: TGdkInterpType = 1;
  GDK_INTERP_BILINEAR: TGdkInterpType = 2;
  GDK_INTERP_HYPER: TGdkInterpType = 3;

type
  TGdkPixbufRotation = DWord;
const
  { GdkPixbufRotation }
  GDK_PIXBUF_ROTATE_NONE: TGdkPixbufRotation = 0;
  GDK_PIXBUF_ROTATE_COUNTERCLOCKWISE: TGdkPixbufRotation = 90;
  GDK_PIXBUF_ROTATE_UPSIDEDOWN: TGdkPixbufRotation = 180;
  GDK_PIXBUF_ROTATE_CLOCKWISE: TGdkPixbufRotation = 270;

type
  TGdkPixbufAlphaMode = DWord;
const
  { GdkPixbufAlphaMode }
  GDK_PIXBUF_ALPHA_BILEVEL: TGdkPixbufAlphaMode = 0;
  GDK_PIXBUF_ALPHA_FULL: TGdkPixbufAlphaMode = 1;

type
  TGdkPixbufError = DWord;
const
  { GdkPixbufError }
  GDK_PIXBUF_ERROR_CORRUPT_IMAGE: TGdkPixbufError = 0;
  GDK_PIXBUF_ERROR_INSUFFICIENT_MEMORY: TGdkPixbufError = 1;
  GDK_PIXBUF_ERROR_BAD_OPTION: TGdkPixbufError = 2;
  GDK_PIXBUF_ERROR_UNKNOWN_TYPE: TGdkPixbufError = 3;
  GDK_PIXBUF_ERROR_UNSUPPORTED_OPERATION: TGdkPixbufError = 4;
  GDK_PIXBUF_ERROR_FAILED: TGdkPixbufError = 5;
  GDK_PIXBUF_ERROR_INCOMPLETE_ANIMATION: TGdkPixbufError = 6;

type
  TGdkPixdataDumpType = DWord;
const
  { GdkPixdataDumpType }
  GDK_PIXDATA_DUMP_PIXDATA_STREAM: TGdkPixdataDumpType = 0;
  GDK_PIXDATA_DUMP_PIXDATA_STRUCT: TGdkPixdataDumpType = 1;
  GDK_PIXDATA_DUMP_MACROS: TGdkPixdataDumpType = 2;
  GDK_PIXDATA_DUMP_GTYPES: TGdkPixdataDumpType = 0;
  GDK_PIXDATA_DUMP_CTYPES: TGdkPixdataDumpType = 256;
  GDK_PIXDATA_DUMP_STATIC: TGdkPixdataDumpType = 512;
  GDK_PIXDATA_DUMP_CONST: TGdkPixdataDumpType = 1024;
  GDK_PIXDATA_DUMP_RLE_DECODER: TGdkPixdataDumpType = 65536;

type
  TGdkPixdataType = DWord;
const
  { GdkPixdataType }
  GDK_PIXDATA_COLOR_TYPE_RGB: TGdkPixdataType = 1;
  GDK_PIXDATA_COLOR_TYPE_RGBA: TGdkPixdataType = 2;
  GDK_PIXDATA_COLOR_TYPE_MASK: TGdkPixdataType = 255;
  GDK_PIXDATA_SAMPLE_WIDTH_8: TGdkPixdataType = 65536;
  GDK_PIXDATA_SAMPLE_WIDTH_MASK: TGdkPixdataType = 983040;
  GDK_PIXDATA_ENCODING_RAW: TGdkPixdataType = 16777216;
  GDK_PIXDATA_ENCODING_RLE: TGdkPixdataType = 33554432;
  GDK_PIXDATA_ENCODING_MASK: TGdkPixdataType = 251658240;
type

  PPGdkColorspace = ^PGdkColorspace;
  PGdkColorspace = ^TGdkColorspace;

  PPGdkInterpType = ^PGdkInterpType;
  PGdkInterpType = ^TGdkInterpType;

  PPGdkPixbuf = ^PGdkPixbuf;
  PGdkPixbuf = ^TGdkPixbuf;

  PPGdkPixbufDestroyNotify = ^PGdkPixbufDestroyNotify;
  PGdkPixbufDestroyNotify = ^TGdkPixbufDestroyNotify;
  TGdkPixbufDestroyNotify = procedure(pixels: Pguint8; data: gpointer); cdecl;

  PPGdkPixbufFormat = ^PGdkPixbufFormat;
  PGdkPixbufFormat = ^TGdkPixbufFormat;

  PPGdkPixbufRotation = ^PGdkPixbufRotation;
  PGdkPixbufRotation = ^TGdkPixbufRotation;

  PPGdkPixbufSaveFunc = ^PGdkPixbufSaveFunc;
  PGdkPixbufSaveFunc = ^TGdkPixbufSaveFunc;
  TGdkPixbufSaveFunc = function(buf: Pgchar; count: gsize; error: PPGError; data: gpointer): gboolean; cdecl;
  TGdkPixbuf = object(TGObject)
    function new(colorspace: TGdkColorspace; has_alpha: gboolean; bits_per_sample: gint; width: gint; height: gint): PGdkPixbuf; cdecl; inline; static;
    function new_from_bytes(data: PGBytes; colorspace: TGdkColorspace; has_alpha: gboolean; bits_per_sample: gint; width: gint; height: gint; rowstride: gint): PGdkPixbuf; cdecl; inline; static;
    function new_from_data(data: Pguint8; colorspace: TGdkColorspace; has_alpha: gboolean; bits_per_sample: gint; width: gint; height: gint; rowstride: gint; destroy_fn: TGdkPixbufDestroyNotify; destroy_fn_data: gpointer): PGdkPixbuf; cdecl; inline; static;
    function new_from_file(filename: Pgchar; error: PPGError): PGdkPixbuf; cdecl; inline; static;
    function new_from_file_at_scale(filename: Pgchar; width: gint; height: gint; preserve_aspect_ratio: gboolean; error: PPGError): PGdkPixbuf; cdecl; inline; static;
    function new_from_file_at_size(filename: Pgchar; width: gint; height: gint; error: PPGError): PGdkPixbuf; cdecl; inline; static;
    function new_from_resource(resource_path: Pgchar; error: PPGError): PGdkPixbuf; cdecl; inline; static;
    function new_from_resource_at_scale(resource_path: Pgchar; width: gint; height: gint; preserve_aspect_ratio: gboolean; error: PPGError): PGdkPixbuf; cdecl; inline; static;
    function new_from_stream(stream: PGInputStream; cancellable: PGCancellable; error: PPGError): PGdkPixbuf; cdecl; inline; static;
    function new_from_stream_at_scale(stream: PGInputStream; width: gint; height: gint; preserve_aspect_ratio: gboolean; cancellable: PGCancellable; error: PPGError): PGdkPixbuf; cdecl; inline; static;
    function new_from_stream_finish(async_result: PGAsyncResult; error: PPGError): PGdkPixbuf; cdecl; inline; static;
    function new_from_xpm_data(data: PPgchar): PGdkPixbuf; cdecl; inline; static;
    function calculate_rowstride(colorspace: TGdkColorspace; has_alpha: gboolean; bits_per_sample: gint; width: gint; height: gint): gint; cdecl; inline; static;
    function get_file_info(filename: Pgchar; width: Pgint; height: Pgint): PGdkPixbufFormat; cdecl; inline; static;
    procedure get_file_info_async(filename: Pgchar; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer); cdecl; inline; static;
    function get_file_info_finish(async_result: PGAsyncResult; width: Pgint; height: Pgint; error: PPGError): PGdkPixbufFormat; cdecl; inline; static;
    function get_formats: PGSList; cdecl; inline; static;
    procedure new_from_stream_async(stream: PGInputStream; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer); cdecl; inline; static;
    procedure new_from_stream_at_scale_async(stream: PGInputStream; width: gint; height: gint; preserve_aspect_ratio: gboolean; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer); cdecl; inline; static;
    function save_to_stream_finish(async_result: PGAsyncResult; error: PPGError): gboolean; cdecl; inline; static;
    function add_alpha(substitute_color: gboolean; r: guint8; g: guint8; b: guint8): PGdkPixbuf; cdecl; inline;
    function apply_embedded_orientation: PGdkPixbuf; cdecl; inline;
    procedure composite(dest: PGdkPixbuf; dest_x: gint; dest_y: gint; dest_width: gint; dest_height: gint; offset_x: gdouble; offset_y: gdouble; scale_x: gdouble; scale_y: gdouble; interp_type: TGdkInterpType; overall_alpha: gint); cdecl; inline;
    procedure composite_color(dest: PGdkPixbuf; dest_x: gint; dest_y: gint; dest_width: gint; dest_height: gint; offset_x: gdouble; offset_y: gdouble; scale_x: gdouble; scale_y: gdouble; interp_type: TGdkInterpType; overall_alpha: gint; check_x: gint; check_y: gint; check_size: gint; color1: guint32; color2: guint32); cdecl; inline;
    function composite_color_simple(dest_width: gint; dest_height: gint; interp_type: TGdkInterpType; overall_alpha: gint; check_size: gint; color1: guint32; color2: guint32): PGdkPixbuf; cdecl; inline;
    function copy: PGdkPixbuf; cdecl; inline;
    procedure copy_area(src_x: gint; src_y: gint; width: gint; height: gint; dest_pixbuf: PGdkPixbuf; dest_x: gint; dest_y: gint); cdecl; inline;
    function copy_options(dest_pixbuf: PGdkPixbuf): gboolean; cdecl; inline;
    procedure fill(pixel: guint32); cdecl; inline;
    function flip(horizontal: gboolean): PGdkPixbuf; cdecl; inline;
    function get_bits_per_sample: gint; cdecl; inline;
    function get_byte_length: gsize; cdecl; inline;
    function get_colorspace: TGdkColorspace; cdecl; inline;
    function get_has_alpha: gboolean; cdecl; inline;
    function get_height: gint; cdecl; inline;
    function get_n_channels: gint; cdecl; inline;
    function get_option(key: Pgchar): Pgchar; cdecl; inline;
    function get_options: PGHashTable; cdecl; inline;
    function get_pixels: Pguint8; cdecl; inline;
    function get_pixels_with_length(length: Pguint): Pguint8; cdecl; inline;
    function get_rowstride: gint; cdecl; inline;
    function get_width: gint; cdecl; inline;
    function new_subpixbuf(src_x: gint; src_y: gint; width: gint; height: gint): PGdkPixbuf; cdecl; inline;
    function read_pixel_bytes: PGBytes; cdecl; inline;
    function read_pixels: Pguint8; cdecl; inline;
    function remove_option(key: Pgchar): gboolean; cdecl; inline;
    function rotate_simple(angle: TGdkPixbufRotation): PGdkPixbuf; cdecl; inline;
    procedure saturate_and_pixelate(dest: PGdkPixbuf; saturation: gfloat; pixelate: gboolean); cdecl; inline;
    //function save(filename: Pgchar; type_: Pgchar; error: PPGError; args: array of const): gboolean; cdecl; inline;
    //function save_to_buffer(buffer: PPgchar; buffer_size: Pgsize; type_: Pgchar; error: PPGError; args: array of const): gboolean; cdecl; inline;
    function save_to_bufferv(buffer: PPgchar; buffer_size: Pgsize; type_: Pgchar; option_keys: PPgchar; option_values: PPgchar; error: PPGError): gboolean; cdecl; inline;
    //function save_to_callback(save_func: TGdkPixbufSaveFunc; user_data: gpointer; type_: Pgchar; error: PPGError; args: array of const): gboolean; cdecl; inline;
    function save_to_callbackv(save_func: TGdkPixbufSaveFunc; user_data: gpointer; type_: Pgchar; option_keys: PPgchar; option_values: PPgchar; error: PPGError): gboolean; cdecl; inline;
    //function save_to_stream(stream: PGOutputStream; type_: Pgchar; cancellable: PGCancellable; error: PPGError; args: array of const): gboolean; cdecl; inline;
    //procedure save_to_stream_async(stream: PGOutputStream; type_: Pgchar; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer; args: array of const); cdecl; inline;
    function save_to_streamv(stream: PGOutputStream; type_: Pgchar; option_keys: PPgchar; option_values: PPgchar; cancellable: PGCancellable; error: PPGError): gboolean; cdecl; inline;
    procedure save_to_streamv_async(stream: PGOutputStream; type_: Pgchar; option_keys: PPgchar; option_values: PPgchar; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer); cdecl; inline;
    function savev(filename: Pgchar; type_: Pgchar; option_keys: PPgchar; option_values: PPgchar; error: PPGError): gboolean; cdecl; inline;
    procedure scale(dest: PGdkPixbuf; dest_x: gint; dest_y: gint; dest_width: gint; dest_height: gint; offset_x: gdouble; offset_y: gdouble; scale_x: gdouble; scale_y: gdouble; interp_type: TGdkInterpType); cdecl; inline;
    function scale_simple(dest_width: gint; dest_height: gint; interp_type: TGdkInterpType): PGdkPixbuf; cdecl; inline;
    function set_option(key: Pgchar; value: Pgchar): gboolean; cdecl; inline;
    property bits_per_sample: gint read get_bits_per_sample  { property is writeable but setter not declared } ;
    property colorspace: TGdkColorspace read get_colorspace  { property is writeable but setter not declared } ;
    property has_alpha: gboolean read get_has_alpha  { property is writeable but setter not declared } ;
    property height: gint read get_height  { property is writeable but setter not declared } ;
    property n_channels: gint read get_n_channels  { property is writeable but setter not declared } ;
    //property pixel_bytes: UNABLE_TO_FIND_TYPE_FOR_PROPERTY read get_pixel_bytes  { property is writeable but setter not declared } ;
    property pixels: Pguint8 read get_pixels  { property is writeable but setter not declared } ;
    property rowstride: gint read get_rowstride  { property is writeable but setter not declared } ;
    property width: gint read get_width  { property is writeable but setter not declared } ;
  end;

  PPGdkPixdata = ^PGdkPixdata;
  PGdkPixdata = ^TGdkPixdata;
  TGdkPixdata = object
    magic: guint32;
    length: gint32;
    pixdata_type: guint32;
    rowstride: guint32;
    width: guint32;
    height: guint32;
    pixel_data: Pguint8;
  end;
  TGdkPixbufFormat = object
    function copy: PGdkPixbufFormat; cdecl; inline;
    procedure free; cdecl; inline;
    function get_description: Pgchar; cdecl; inline;
    function get_extensions: PPgchar; cdecl; inline;
    function get_license: Pgchar; cdecl; inline;
    function get_mime_types: PPgchar; cdecl; inline;
    function get_name: Pgchar; cdecl; inline;
    function is_disabled: gboolean; cdecl; inline;
    function is_save_option_supported(option_key: Pgchar): gboolean; cdecl; inline;
    function is_scalable: gboolean; cdecl; inline;
    function is_writable: gboolean; cdecl; inline;
    procedure set_disabled(disabled: gboolean); cdecl; inline;
  end;

  PPGdkPixbufAlphaMode = ^PGdkPixbufAlphaMode;
  PGdkPixbufAlphaMode = ^TGdkPixbufAlphaMode;

  PPGdkPixbufAnimation = ^PGdkPixbufAnimation;
  PGdkPixbufAnimation = ^TGdkPixbufAnimation;

  PPGdkPixbufAnimationIter = ^PGdkPixbufAnimationIter;
  PGdkPixbufAnimationIter = ^TGdkPixbufAnimationIter;
  TGdkPixbufAnimation = object(TGObject)
    function new_from_file(filename: Pgchar; error: PPGError): PGdkPixbufAnimation; cdecl; inline; static;
    function new_from_resource(resource_path: Pgchar; error: PPGError): PGdkPixbufAnimation; cdecl; inline; static;
    function new_from_stream(stream: PGInputStream; cancellable: PGCancellable; error: PPGError): PGdkPixbufAnimation; cdecl; inline; static;
    function new_from_stream_finish(async_result: PGAsyncResult; error: PPGError): PGdkPixbufAnimation; cdecl; inline; static;
    procedure new_from_stream_async(stream: PGInputStream; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer); cdecl; inline; static;
    function get_height: gint; cdecl; inline;
    function get_iter(start_time: PGTimeVal): PGdkPixbufAnimationIter; cdecl; inline;
    function get_static_image: PGdkPixbuf; cdecl; inline;
    function get_width: gint; cdecl; inline;
    function is_static_image: gboolean; cdecl; inline;
  end;
  TGdkPixbufAnimationIter = object(TGObject)
    function advance(current_time: PGTimeVal): gboolean; cdecl; inline;
    function get_delay_time: gint; cdecl; inline;
    function get_pixbuf: PGdkPixbuf; cdecl; inline;
    function on_currently_loading_frame: gboolean; cdecl; inline;
  end;

  PPGdkPixbufError = ^PGdkPixbufError;
  PGdkPixbufError = ^TGdkPixbufError;

  PPGdkPixbufLoader = ^PGdkPixbufLoader;
  PGdkPixbufLoader = ^TGdkPixbufLoader;
  TGdkPixbufLoader = object(TGObject)
    priv: gpointer;
    function new: PGdkPixbufLoader; cdecl; inline; static;
    function new_with_mime_type(mime_type: Pgchar; error: PPGError): PGdkPixbufLoader; cdecl; inline; static;
    function new_with_type(image_type: Pgchar; error: PPGError): PGdkPixbufLoader; cdecl; inline; static;
    function close(error: PPGError): gboolean; cdecl; inline;
    function get_animation: PGdkPixbufAnimation; cdecl; inline;
    function get_format: PGdkPixbufFormat; cdecl; inline;
    function get_pixbuf: PGdkPixbuf; cdecl; inline;
    procedure set_size(width: gint; height: gint); cdecl; inline;
    function write(buf: Pguint8; count: gsize; error: PPGError): gboolean; cdecl; inline;
    function write_bytes(buffer: PGBytes; error: PPGError): gboolean; cdecl; inline;
  end;

  PPGdkPixbufLoaderClass = ^PGdkPixbufLoaderClass;
  PGdkPixbufLoaderClass = ^TGdkPixbufLoaderClass;
  TGdkPixbufLoaderClass = object
    parent_class: TGObjectClass;
    size_prepared: procedure(loader: PGdkPixbufLoader; width: gint; height: gint); cdecl;
    area_prepared: procedure(loader: PGdkPixbufLoader); cdecl;
    area_updated: procedure(loader: PGdkPixbufLoader; x: gint; y: gint; width: gint; height: gint); cdecl;
    closed: procedure(loader: PGdkPixbufLoader); cdecl;
  end;

  PPGdkPixbufSimpleAnim = ^PGdkPixbufSimpleAnim;
  PGdkPixbufSimpleAnim = ^TGdkPixbufSimpleAnim;
  TGdkPixbufSimpleAnim = object(TGdkPixbufAnimation)
    function new(width: gint; height: gint; rate: gfloat): PGdkPixbufSimpleAnim; cdecl; inline; static;
    procedure add_frame(pixbuf: PGdkPixbuf); cdecl; inline;
    function get_loop: gboolean; cdecl; inline;
    procedure set_loop(loop: gboolean); cdecl; inline;
    property loop: gboolean read get_loop write set_loop;
  end;

  PPGdkPixbufSimpleAnimClass = ^PGdkPixbufSimpleAnimClass;
  PGdkPixbufSimpleAnimClass = ^TGdkPixbufSimpleAnimClass;
  TGdkPixbufSimpleAnimClass = object
  end;

  PPGdkPixbufSimpleAnimIter = ^PGdkPixbufSimpleAnimIter;
  PGdkPixbufSimpleAnimIter = ^TGdkPixbufSimpleAnimIter;
  TGdkPixbufSimpleAnimIter = object(TGdkPixbufAnimationIter)
  end;

  PPGdkPixdataDumpType = ^PGdkPixdataDumpType;
  PGdkPixdataDumpType = ^TGdkPixdataDumpType;

  PPGdkPixdataType = ^PGdkPixdataType;
  PGdkPixdataType = ^TGdkPixdataType;

var
gdk_pixbuf_add_alpha: function(pixbuf: PGdkPixbuf; substitute_color: gboolean; r: guint8; g: guint8; b: guint8): PGdkPixbuf; cdecl;
gdk_pixbuf_animation_get_height: function(animation: PGdkPixbufAnimation): gint; cdecl;
gdk_pixbuf_animation_get_iter: function(animation: PGdkPixbufAnimation; start_time: PGTimeVal): PGdkPixbufAnimationIter; cdecl;
gdk_pixbuf_animation_get_static_image: function(animation: PGdkPixbufAnimation): PGdkPixbuf; cdecl;
gdk_pixbuf_animation_get_type: function:TGType; cdecl;
gdk_pixbuf_animation_get_width: function(animation: PGdkPixbufAnimation): gint; cdecl;
gdk_pixbuf_animation_is_static_image: function(animation: PGdkPixbufAnimation): gboolean; cdecl;
gdk_pixbuf_animation_iter_advance: function(iter: PGdkPixbufAnimationIter; current_time: PGTimeVal): gboolean; cdecl;
gdk_pixbuf_animation_iter_get_delay_time: function(iter: PGdkPixbufAnimationIter): gint; cdecl;
gdk_pixbuf_animation_iter_get_pixbuf: function(iter: PGdkPixbufAnimationIter): PGdkPixbuf; cdecl;
gdk_pixbuf_animation_iter_get_type: function:TGType; cdecl;
gdk_pixbuf_animation_iter_on_currently_loading_frame: function(iter: PGdkPixbufAnimationIter): gboolean; cdecl;
gdk_pixbuf_animation_new_from_file: function(filename: Pgchar; error: PPGError): PGdkPixbufAnimation; cdecl;
gdk_pixbuf_animation_new_from_resource: function(resource_path: Pgchar; error: PPGError): PGdkPixbufAnimation; cdecl;
gdk_pixbuf_animation_new_from_stream: function(stream: PGInputStream; cancellable: PGCancellable; error: PPGError): PGdkPixbufAnimation; cdecl;
gdk_pixbuf_animation_new_from_stream_async: procedure(stream: PGInputStream; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer); cdecl;
gdk_pixbuf_animation_new_from_stream_finish: function(async_result: PGAsyncResult; error: PPGError): PGdkPixbufAnimation; cdecl;
gdk_pixbuf_apply_embedded_orientation: function(src: PGdkPixbuf): PGdkPixbuf; cdecl;
gdk_pixbuf_calculate_rowstride: function(colorspace: TGdkColorspace; has_alpha: gboolean; bits_per_sample: gint; width: gint; height: gint): gint; cdecl;
gdk_pixbuf_composite: procedure(src: PGdkPixbuf; dest: PGdkPixbuf; dest_x: gint; dest_y: gint; dest_width: gint; dest_height: gint; offset_x: gdouble; offset_y: gdouble; scale_x: gdouble; scale_y: gdouble; interp_type: TGdkInterpType; overall_alpha: gint); cdecl;
gdk_pixbuf_composite_color: procedure(src: PGdkPixbuf; dest: PGdkPixbuf; dest_x: gint; dest_y: gint; dest_width: gint; dest_height: gint; offset_x: gdouble; offset_y: gdouble; scale_x: gdouble; scale_y: gdouble; interp_type: TGdkInterpType; overall_alpha: gint; check_x: gint; check_y: gint; check_size: gint; color1: guint32; color2: guint32); cdecl;
gdk_pixbuf_composite_color_simple: function(src: PGdkPixbuf; dest_width: gint; dest_height: gint; interp_type: TGdkInterpType; overall_alpha: gint; check_size: gint; color1: guint32; color2: guint32): PGdkPixbuf; cdecl;
gdk_pixbuf_copy: function(pixbuf: PGdkPixbuf): PGdkPixbuf; cdecl;
gdk_pixbuf_copy_area: procedure(src_pixbuf: PGdkPixbuf; src_x: gint; src_y: gint; width: gint; height: gint; dest_pixbuf: PGdkPixbuf; dest_x: gint; dest_y: gint); cdecl;
gdk_pixbuf_copy_options: function(src_pixbuf: PGdkPixbuf; dest_pixbuf: PGdkPixbuf): gboolean; cdecl;
gdk_pixbuf_error_quark: function: TGQuark; cdecl;
gdk_pixbuf_fill: procedure(pixbuf: PGdkPixbuf; pixel: guint32); cdecl;
gdk_pixbuf_flip: function(src: PGdkPixbuf; horizontal: gboolean): PGdkPixbuf; cdecl;
gdk_pixbuf_format_copy: function(format: PGdkPixbufFormat): PGdkPixbufFormat; cdecl;
gdk_pixbuf_format_free: procedure(format: PGdkPixbufFormat); cdecl;
gdk_pixbuf_format_get_description: function(format: PGdkPixbufFormat): Pgchar; cdecl;
gdk_pixbuf_format_get_extensions: function(format: PGdkPixbufFormat): PPgchar; cdecl;
gdk_pixbuf_format_get_license: function(format: PGdkPixbufFormat): Pgchar; cdecl;
gdk_pixbuf_format_get_mime_types: function(format: PGdkPixbufFormat): PPgchar; cdecl;
gdk_pixbuf_format_get_name: function(format: PGdkPixbufFormat): Pgchar; cdecl;
gdk_pixbuf_format_get_type: function:TGType; cdecl;
gdk_pixbuf_format_is_disabled: function(format: PGdkPixbufFormat): gboolean; cdecl;
gdk_pixbuf_format_is_save_option_supported: function(format: PGdkPixbufFormat; option_key: Pgchar): gboolean; cdecl;
gdk_pixbuf_format_is_scalable: function(format: PGdkPixbufFormat): gboolean; cdecl;
gdk_pixbuf_format_is_writable: function(format: PGdkPixbufFormat): gboolean; cdecl;
gdk_pixbuf_format_set_disabled: procedure(format: PGdkPixbufFormat; disabled: gboolean); cdecl;
gdk_pixbuf_get_bits_per_sample: function(pixbuf: PGdkPixbuf): gint; cdecl;
gdk_pixbuf_get_byte_length: function(pixbuf: PGdkPixbuf): gsize; cdecl;
gdk_pixbuf_get_colorspace: function(pixbuf: PGdkPixbuf): TGdkColorspace; cdecl;
gdk_pixbuf_get_file_info: function(filename: Pgchar; width: Pgint; height: Pgint): PGdkPixbufFormat; cdecl;
gdk_pixbuf_get_file_info_async: procedure(filename: Pgchar; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer); cdecl;
gdk_pixbuf_get_file_info_finish: function(async_result: PGAsyncResult; width: Pgint; height: Pgint; error: PPGError): PGdkPixbufFormat; cdecl;
gdk_pixbuf_get_formats: function: PGSList; cdecl;
gdk_pixbuf_get_has_alpha: function(pixbuf: PGdkPixbuf): gboolean; cdecl;
gdk_pixbuf_get_height: function(pixbuf: PGdkPixbuf): gint; cdecl;
gdk_pixbuf_get_n_channels: function(pixbuf: PGdkPixbuf): gint; cdecl;
gdk_pixbuf_get_option: function(pixbuf: PGdkPixbuf; key: Pgchar): Pgchar; cdecl;
gdk_pixbuf_get_options: function(pixbuf: PGdkPixbuf): PGHashTable; cdecl;
gdk_pixbuf_get_pixels: function(pixbuf: PGdkPixbuf): Pguint8; cdecl;
gdk_pixbuf_get_pixels_with_length: function(pixbuf: PGdkPixbuf; length: Pguint): Pguint8; cdecl;
gdk_pixbuf_get_rowstride: function(pixbuf: PGdkPixbuf): gint; cdecl;
gdk_pixbuf_get_type: function:TGType; cdecl;
gdk_pixbuf_get_width: function(pixbuf: PGdkPixbuf): gint; cdecl;
gdk_pixbuf_loader_close: function(loader: PGdkPixbufLoader; error: PPGError): gboolean; cdecl;
gdk_pixbuf_loader_get_animation: function(loader: PGdkPixbufLoader): PGdkPixbufAnimation; cdecl;
gdk_pixbuf_loader_get_format: function(loader: PGdkPixbufLoader): PGdkPixbufFormat; cdecl;
gdk_pixbuf_loader_get_pixbuf: function(loader: PGdkPixbufLoader): PGdkPixbuf; cdecl;
gdk_pixbuf_loader_get_type: function:TGType; cdecl;
gdk_pixbuf_loader_new: function: PGdkPixbufLoader; cdecl;
gdk_pixbuf_loader_new_with_mime_type: function(mime_type: Pgchar; error: PPGError): PGdkPixbufLoader; cdecl;
gdk_pixbuf_loader_new_with_type: function(image_type: Pgchar; error: PPGError): PGdkPixbufLoader; cdecl;
gdk_pixbuf_loader_set_size: procedure(loader: PGdkPixbufLoader; width: gint; height: gint); cdecl;
gdk_pixbuf_loader_write: function(loader: PGdkPixbufLoader; buf: Pguint8; count: gsize; error: PPGError): gboolean; cdecl;
gdk_pixbuf_loader_write_bytes: function(loader: PGdkPixbufLoader; buffer: PGBytes; error: PPGError): gboolean; cdecl;
gdk_pixbuf_new: function(colorspace: TGdkColorspace; has_alpha: gboolean; bits_per_sample: gint; width: gint; height: gint): PGdkPixbuf; cdecl;
gdk_pixbuf_new_from_bytes: function(data: PGBytes; colorspace: TGdkColorspace; has_alpha: gboolean; bits_per_sample: gint; width: gint; height: gint; rowstride: gint): PGdkPixbuf; cdecl;
gdk_pixbuf_new_from_data: function(data: Pguint8; colorspace: TGdkColorspace; has_alpha: gboolean; bits_per_sample: gint; width: gint; height: gint; rowstride: gint; destroy_fn: TGdkPixbufDestroyNotify; destroy_fn_data: gpointer): PGdkPixbuf; cdecl;
gdk_pixbuf_new_from_file: function(filename: Pgchar; error: PPGError): PGdkPixbuf; cdecl;
gdk_pixbuf_new_from_file_at_scale: function(filename: Pgchar; width: gint; height: gint; preserve_aspect_ratio: gboolean; error: PPGError): PGdkPixbuf; cdecl;
gdk_pixbuf_new_from_file_at_size: function(filename: Pgchar; width: gint; height: gint; error: PPGError): PGdkPixbuf; cdecl;
gdk_pixbuf_new_from_resource: function(resource_path: Pgchar; error: PPGError): PGdkPixbuf; cdecl;
gdk_pixbuf_new_from_resource_at_scale: function(resource_path: Pgchar; width: gint; height: gint; preserve_aspect_ratio: gboolean; error: PPGError): PGdkPixbuf; cdecl;
gdk_pixbuf_new_from_stream: function(stream: PGInputStream; cancellable: PGCancellable; error: PPGError): PGdkPixbuf; cdecl;
gdk_pixbuf_new_from_stream_async: procedure(stream: PGInputStream; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer); cdecl;
gdk_pixbuf_new_from_stream_at_scale: function(stream: PGInputStream; width: gint; height: gint; preserve_aspect_ratio: gboolean; cancellable: PGCancellable; error: PPGError): PGdkPixbuf; cdecl;
gdk_pixbuf_new_from_stream_at_scale_async: procedure(stream: PGInputStream; width: gint; height: gint; preserve_aspect_ratio: gboolean; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer); cdecl;
gdk_pixbuf_new_from_stream_finish: function(async_result: PGAsyncResult; error: PPGError): PGdkPixbuf; cdecl;
gdk_pixbuf_new_from_xpm_data: function(data: PPgchar): PGdkPixbuf; cdecl;
gdk_pixbuf_new_subpixbuf: function(src_pixbuf: PGdkPixbuf; src_x: gint; src_y: gint; width: gint; height: gint): PGdkPixbuf; cdecl;
gdk_pixbuf_read_pixel_bytes: function(pixbuf: PGdkPixbuf): PGBytes; cdecl;
gdk_pixbuf_read_pixels: function(pixbuf: PGdkPixbuf): Pguint8; cdecl;
gdk_pixbuf_remove_option: function(pixbuf: PGdkPixbuf; key: Pgchar): gboolean; cdecl;
gdk_pixbuf_rotate_simple: function(src: PGdkPixbuf; angle: TGdkPixbufRotation): PGdkPixbuf; cdecl;
gdk_pixbuf_saturate_and_pixelate: procedure(src: PGdkPixbuf; dest: PGdkPixbuf; saturation: gfloat; pixelate: gboolean); cdecl;
gdk_pixbuf_save: function(pixbuf: PGdkPixbuf; filename: Pgchar; type_: Pgchar; error: PPGError; args: array of const): gboolean; cdecl;
gdk_pixbuf_save_to_buffer: function(pixbuf: PGdkPixbuf; buffer: PPgchar; buffer_size: Pgsize; type_: Pgchar; error: PPGError; args: array of const): gboolean; cdecl;
gdk_pixbuf_save_to_bufferv: function(pixbuf: PGdkPixbuf; buffer: PPgchar; buffer_size: Pgsize; type_: Pgchar; option_keys: PPgchar; option_values: PPgchar; error: PPGError): gboolean; cdecl;
gdk_pixbuf_save_to_callback: function(pixbuf: PGdkPixbuf; save_func: TGdkPixbufSaveFunc; user_data: gpointer; type_: Pgchar; error: PPGError; args: array of const): gboolean; cdecl;
gdk_pixbuf_save_to_callbackv: function(pixbuf: PGdkPixbuf; save_func: TGdkPixbufSaveFunc; user_data: gpointer; type_: Pgchar; option_keys: PPgchar; option_values: PPgchar; error: PPGError): gboolean; cdecl;
gdk_pixbuf_save_to_stream: function(pixbuf: PGdkPixbuf; stream: PGOutputStream; type_: Pgchar; cancellable: PGCancellable; error: PPGError; args: array of const): gboolean; cdecl;
gdk_pixbuf_save_to_stream_async: procedure(pixbuf: PGdkPixbuf; stream: PGOutputStream; type_: Pgchar; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer; args: array of const); cdecl;
gdk_pixbuf_save_to_stream_finish: function(async_result: PGAsyncResult; error: PPGError): gboolean; cdecl;
gdk_pixbuf_save_to_streamv: function(pixbuf: PGdkPixbuf; stream: PGOutputStream; type_: Pgchar; option_keys: PPgchar; option_values: PPgchar; cancellable: PGCancellable; error: PPGError): gboolean; cdecl;
gdk_pixbuf_save_to_streamv_async: procedure(pixbuf: PGdkPixbuf; stream: PGOutputStream; type_: Pgchar; option_keys: PPgchar; option_values: PPgchar; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer); cdecl;
gdk_pixbuf_savev: function(pixbuf: PGdkPixbuf; filename: Pgchar; type_: Pgchar; option_keys: PPgchar; option_values: PPgchar; error: PPGError): gboolean; cdecl;
gdk_pixbuf_scale: procedure(src: PGdkPixbuf; dest: PGdkPixbuf; dest_x: gint; dest_y: gint; dest_width: gint; dest_height: gint; offset_x: gdouble; offset_y: gdouble; scale_x: gdouble; scale_y: gdouble; interp_type: TGdkInterpType); cdecl;
gdk_pixbuf_scale_simple: function(src: PGdkPixbuf; dest_width: gint; dest_height: gint; interp_type: TGdkInterpType): PGdkPixbuf; cdecl;
gdk_pixbuf_set_option: function(pixbuf: PGdkPixbuf; key: Pgchar; value: Pgchar): gboolean; cdecl;
gdk_pixbuf_simple_anim_add_frame: procedure(animation: PGdkPixbufSimpleAnim; pixbuf: PGdkPixbuf); cdecl;
gdk_pixbuf_simple_anim_get_loop: function(animation: PGdkPixbufSimpleAnim): gboolean; cdecl;
gdk_pixbuf_simple_anim_get_type: function:TGType; cdecl;
gdk_pixbuf_simple_anim_iter_get_type: function:TGType; cdecl;
gdk_pixbuf_simple_anim_new: function(width: gint; height: gint; rate: gfloat): PGdkPixbufSimpleAnim; cdecl;
gdk_pixbuf_simple_anim_set_loop: procedure(animation: PGdkPixbufSimpleAnim; loop: gboolean); cdecl;
implementation
uses
  DynLibs;


function TGdkPixbuf.new(colorspace: TGdkColorspace; has_alpha: gboolean; bits_per_sample: gint; width: gint; height: gint): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_new(colorspace, has_alpha, bits_per_sample, width, height);
end;

function TGdkPixbuf.new_from_bytes(data: PGBytes; colorspace: TGdkColorspace; has_alpha: gboolean; bits_per_sample: gint; width: gint; height: gint; rowstride: gint): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_new_from_bytes(data, colorspace, has_alpha, bits_per_sample, width, height, rowstride);
end;

function TGdkPixbuf.new_from_data(data: Pguint8; colorspace: TGdkColorspace; has_alpha: gboolean; bits_per_sample: gint; width: gint; height: gint; rowstride: gint; destroy_fn: TGdkPixbufDestroyNotify; destroy_fn_data: gpointer): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_new_from_data(data, colorspace, has_alpha, bits_per_sample, width, height, rowstride, destroy_fn, destroy_fn_data);
end;

function TGdkPixbuf.new_from_file(filename: Pgchar; error: PPGError): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_new_from_file(filename, error);
end;

function TGdkPixbuf.new_from_file_at_scale(filename: Pgchar; width: gint; height: gint; preserve_aspect_ratio: gboolean; error: PPGError): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_new_from_file_at_scale(filename, width, height, preserve_aspect_ratio, error);
end;

function TGdkPixbuf.new_from_file_at_size(filename: Pgchar; width: gint; height: gint; error: PPGError): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_new_from_file_at_size(filename, width, height, error);
end;

function TGdkPixbuf.new_from_resource(resource_path: Pgchar; error: PPGError): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_new_from_resource(resource_path, error);
end;

function TGdkPixbuf.new_from_resource_at_scale(resource_path: Pgchar; width: gint; height: gint; preserve_aspect_ratio: gboolean; error: PPGError): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_new_from_resource_at_scale(resource_path, width, height, preserve_aspect_ratio, error);
end;

function TGdkPixbuf.new_from_stream(stream: PGInputStream; cancellable: PGCancellable; error: PPGError): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_new_from_stream(stream, cancellable, error);
end;

function TGdkPixbuf.new_from_stream_at_scale(stream: PGInputStream; width: gint; height: gint; preserve_aspect_ratio: gboolean; cancellable: PGCancellable; error: PPGError): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_new_from_stream_at_scale(stream, width, height, preserve_aspect_ratio, cancellable, error);
end;

function TGdkPixbuf.new_from_stream_finish(async_result: PGAsyncResult; error: PPGError): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_new_from_stream_finish(async_result, error);
end;

function TGdkPixbuf.new_from_xpm_data(data: PPgchar): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_new_from_xpm_data(data);
end;

function TGdkPixbuf.calculate_rowstride(colorspace: TGdkColorspace; has_alpha: gboolean; bits_per_sample: gint; width: gint; height: gint): gint; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_calculate_rowstride(colorspace, has_alpha, bits_per_sample, width, height);
end;

function TGdkPixbuf.get_file_info(filename: Pgchar; width: Pgint; height: Pgint): PGdkPixbufFormat; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_get_file_info(filename, width, height);
end;

procedure TGdkPixbuf.get_file_info_async(filename: Pgchar; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer); cdecl;
begin
  GdkPixbuf2.gdk_pixbuf_get_file_info_async(filename, cancellable, callback, user_data);
end;

function TGdkPixbuf.get_file_info_finish(async_result: PGAsyncResult; width: Pgint; height: Pgint; error: PPGError): PGdkPixbufFormat; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_get_file_info_finish(async_result, width, height, error);
end;

function TGdkPixbuf.get_formats: PGSList; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_get_formats();
end;

procedure TGdkPixbuf.new_from_stream_async(stream: PGInputStream; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer); cdecl;
begin
  GdkPixbuf2.gdk_pixbuf_new_from_stream_async(stream, cancellable, callback, user_data);
end;

procedure TGdkPixbuf.new_from_stream_at_scale_async(stream: PGInputStream; width: gint; height: gint; preserve_aspect_ratio: gboolean; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer); cdecl;
begin
  GdkPixbuf2.gdk_pixbuf_new_from_stream_at_scale_async(stream, width, height, preserve_aspect_ratio, cancellable, callback, user_data);
end;

function TGdkPixbuf.save_to_stream_finish(async_result: PGAsyncResult; error: PPGError): gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_save_to_stream_finish(async_result, error);
end;

function TGdkPixbuf.add_alpha(substitute_color: gboolean; r: guint8; g: guint8; b: guint8): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_add_alpha(@self, substitute_color, r, g, b);
end;

function TGdkPixbuf.apply_embedded_orientation: PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_apply_embedded_orientation(@self);
end;

procedure TGdkPixbuf.composite(dest: PGdkPixbuf; dest_x: gint; dest_y: gint; dest_width: gint; dest_height: gint; offset_x: gdouble; offset_y: gdouble; scale_x: gdouble; scale_y: gdouble; interp_type: TGdkInterpType; overall_alpha: gint); cdecl;
begin
  GdkPixbuf2.gdk_pixbuf_composite(@self, dest, dest_x, dest_y, dest_width, dest_height, offset_x, offset_y, scale_x, scale_y, interp_type, overall_alpha);
end;

procedure TGdkPixbuf.composite_color(dest: PGdkPixbuf; dest_x: gint; dest_y: gint; dest_width: gint; dest_height: gint; offset_x: gdouble; offset_y: gdouble; scale_x: gdouble; scale_y: gdouble; interp_type: TGdkInterpType; overall_alpha: gint; check_x: gint; check_y: gint; check_size: gint; color1: guint32; color2: guint32); cdecl;
begin
  GdkPixbuf2.gdk_pixbuf_composite_color(@self, dest, dest_x, dest_y, dest_width, dest_height, offset_x, offset_y, scale_x, scale_y, interp_type, overall_alpha, check_x, check_y, check_size, color1, color2);
end;

function TGdkPixbuf.composite_color_simple(dest_width: gint; dest_height: gint; interp_type: TGdkInterpType; overall_alpha: gint; check_size: gint; color1: guint32; color2: guint32): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_composite_color_simple(@self, dest_width, dest_height, interp_type, overall_alpha, check_size, color1, color2);
end;

function TGdkPixbuf.copy: PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_copy(@self);
end;

procedure TGdkPixbuf.copy_area(src_x: gint; src_y: gint; width: gint; height: gint; dest_pixbuf: PGdkPixbuf; dest_x: gint; dest_y: gint); cdecl;
begin
  GdkPixbuf2.gdk_pixbuf_copy_area(@self, src_x, src_y, width, height, dest_pixbuf, dest_x, dest_y);
end;

function TGdkPixbuf.copy_options(dest_pixbuf: PGdkPixbuf): gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_copy_options(@self, dest_pixbuf);
end;

procedure TGdkPixbuf.fill(pixel: guint32); cdecl;
begin
  GdkPixbuf2.gdk_pixbuf_fill(@self, pixel);
end;

function TGdkPixbuf.flip(horizontal: gboolean): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_flip(@self, horizontal);
end;

function TGdkPixbuf.get_bits_per_sample: gint; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_get_bits_per_sample(@self);
end;

function TGdkPixbuf.get_byte_length: gsize; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_get_byte_length(@self);
end;

function TGdkPixbuf.get_colorspace: TGdkColorspace; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_get_colorspace(@self);
end;

function TGdkPixbuf.get_has_alpha: gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_get_has_alpha(@self);
end;

function TGdkPixbuf.get_height: gint; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_get_height(@self);
end;

function TGdkPixbuf.get_n_channels: gint; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_get_n_channels(@self);
end;

function TGdkPixbuf.get_option(key: Pgchar): Pgchar; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_get_option(@self, key);
end;

function TGdkPixbuf.get_options: PGHashTable; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_get_options(@self);
end;

function TGdkPixbuf.get_pixels: Pguint8; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_get_pixels(@self);
end;

function TGdkPixbuf.get_pixels_with_length(length: Pguint): Pguint8; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_get_pixels_with_length(@self, length);
end;

function TGdkPixbuf.get_rowstride: gint; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_get_rowstride(@self);
end;

function TGdkPixbuf.get_width: gint; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_get_width(@self);
end;

function TGdkPixbuf.new_subpixbuf(src_x: gint; src_y: gint; width: gint; height: gint): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_new_subpixbuf(@self, src_x, src_y, width, height);
end;

function TGdkPixbuf.read_pixel_bytes: PGBytes; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_read_pixel_bytes(@self);
end;

function TGdkPixbuf.read_pixels: Pguint8; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_read_pixels(@self);
end;

function TGdkPixbuf.remove_option(key: Pgchar): gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_remove_option(@self, key);
end;

function TGdkPixbuf.rotate_simple(angle: TGdkPixbufRotation): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_rotate_simple(@self, angle);
end;

procedure TGdkPixbuf.saturate_and_pixelate(dest: PGdkPixbuf; saturation: gfloat; pixelate: gboolean); cdecl;
begin
  GdkPixbuf2.gdk_pixbuf_saturate_and_pixelate(@self, dest, saturation, pixelate);
end;

function TGdkPixbuf.save_to_bufferv(buffer: PPgchar; buffer_size: Pgsize; type_: Pgchar; option_keys: PPgchar; option_values: PPgchar; error: PPGError): gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_save_to_bufferv(@self, buffer, buffer_size, type_, option_keys, option_values, error);
end;

function TGdkPixbuf.save_to_callbackv(save_func: TGdkPixbufSaveFunc; user_data: gpointer; type_: Pgchar; option_keys: PPgchar; option_values: PPgchar; error: PPGError): gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_save_to_callbackv(@self, save_func, user_data, type_, option_keys, option_values, error);
end;

function TGdkPixbuf.save_to_streamv(stream: PGOutputStream; type_: Pgchar; option_keys: PPgchar; option_values: PPgchar; cancellable: PGCancellable; error: PPGError): gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_save_to_streamv(@self, stream, type_, option_keys, option_values, cancellable, error);
end;

procedure TGdkPixbuf.save_to_streamv_async(stream: PGOutputStream; type_: Pgchar; option_keys: PPgchar; option_values: PPgchar; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer); cdecl;
begin
  GdkPixbuf2.gdk_pixbuf_save_to_streamv_async(@self, stream, type_, option_keys, option_values, cancellable, callback, user_data);
end;

function TGdkPixbuf.savev(filename: Pgchar; type_: Pgchar; option_keys: PPgchar; option_values: PPgchar; error: PPGError): gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_savev(@self, filename, type_, option_keys, option_values, error);
end;

procedure TGdkPixbuf.scale(dest: PGdkPixbuf; dest_x: gint; dest_y: gint; dest_width: gint; dest_height: gint; offset_x: gdouble; offset_y: gdouble; scale_x: gdouble; scale_y: gdouble; interp_type: TGdkInterpType); cdecl;
begin
  GdkPixbuf2.gdk_pixbuf_scale(@self, dest, dest_x, dest_y, dest_width, dest_height, offset_x, offset_y, scale_x, scale_y, interp_type);
end;

function TGdkPixbuf.scale_simple(dest_width: gint; dest_height: gint; interp_type: TGdkInterpType): PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_scale_simple(@self, dest_width, dest_height, interp_type);
end;

function TGdkPixbuf.set_option(key: Pgchar; value: Pgchar): gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_set_option(@self, key, value);
end;

function TGdkPixbufFormat.copy: PGdkPixbufFormat; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_format_copy(@self);
end;

procedure TGdkPixbufFormat.free; cdecl;
begin
  GdkPixbuf2.gdk_pixbuf_format_free(@self);
end;

function TGdkPixbufFormat.get_description: Pgchar; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_format_get_description(@self);
end;

function TGdkPixbufFormat.get_extensions: PPgchar; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_format_get_extensions(@self);
end;

function TGdkPixbufFormat.get_license: Pgchar; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_format_get_license(@self);
end;

function TGdkPixbufFormat.get_mime_types: PPgchar; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_format_get_mime_types(@self);
end;

function TGdkPixbufFormat.get_name: Pgchar; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_format_get_name(@self);
end;

function TGdkPixbufFormat.is_disabled: gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_format_is_disabled(@self);
end;

function TGdkPixbufFormat.is_save_option_supported(option_key: Pgchar): gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_format_is_save_option_supported(@self, option_key);
end;

function TGdkPixbufFormat.is_scalable: gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_format_is_scalable(@self);
end;

function TGdkPixbufFormat.is_writable: gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_format_is_writable(@self);
end;

procedure TGdkPixbufFormat.set_disabled(disabled: gboolean); cdecl;
begin
  GdkPixbuf2.gdk_pixbuf_format_set_disabled(@self, disabled);
end;

function TGdkPixbufAnimation.new_from_file(filename: Pgchar; error: PPGError): PGdkPixbufAnimation; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_animation_new_from_file(filename, error);
end;

function TGdkPixbufAnimation.new_from_resource(resource_path: Pgchar; error: PPGError): PGdkPixbufAnimation; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_animation_new_from_resource(resource_path, error);
end;

function TGdkPixbufAnimation.new_from_stream(stream: PGInputStream; cancellable: PGCancellable; error: PPGError): PGdkPixbufAnimation; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_animation_new_from_stream(stream, cancellable, error);
end;

function TGdkPixbufAnimation.new_from_stream_finish(async_result: PGAsyncResult; error: PPGError): PGdkPixbufAnimation; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_animation_new_from_stream_finish(async_result, error);
end;

procedure TGdkPixbufAnimation.new_from_stream_async(stream: PGInputStream; cancellable: PGCancellable; callback: TGAsyncReadyCallback; user_data: gpointer); cdecl;
begin
  GdkPixbuf2.gdk_pixbuf_animation_new_from_stream_async(stream, cancellable, callback, user_data);
end;

function TGdkPixbufAnimation.get_height: gint; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_animation_get_height(@self);
end;

function TGdkPixbufAnimation.get_iter(start_time: PGTimeVal): PGdkPixbufAnimationIter; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_animation_get_iter(@self, start_time);
end;

function TGdkPixbufAnimation.get_static_image: PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_animation_get_static_image(@self);
end;

function TGdkPixbufAnimation.get_width: gint; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_animation_get_width(@self);
end;

function TGdkPixbufAnimation.is_static_image: gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_animation_is_static_image(@self);
end;

function TGdkPixbufAnimationIter.advance(current_time: PGTimeVal): gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_animation_iter_advance(@self, current_time);
end;

function TGdkPixbufAnimationIter.get_delay_time: gint; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_animation_iter_get_delay_time(@self);
end;

function TGdkPixbufAnimationIter.get_pixbuf: PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_animation_iter_get_pixbuf(@self);
end;

function TGdkPixbufAnimationIter.on_currently_loading_frame: gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_animation_iter_on_currently_loading_frame(@self);
end;

function TGdkPixbufLoader.new: PGdkPixbufLoader; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_loader_new();
end;

function TGdkPixbufLoader.new_with_mime_type(mime_type: Pgchar; error: PPGError): PGdkPixbufLoader; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_loader_new_with_mime_type(mime_type, error);
end;

function TGdkPixbufLoader.new_with_type(image_type: Pgchar; error: PPGError): PGdkPixbufLoader; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_loader_new_with_type(image_type, error);
end;

function TGdkPixbufLoader.close(error: PPGError): gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_loader_close(@self, error);
end;

function TGdkPixbufLoader.get_animation: PGdkPixbufAnimation; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_loader_get_animation(@self);
end;

function TGdkPixbufLoader.get_format: PGdkPixbufFormat; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_loader_get_format(@self);
end;

function TGdkPixbufLoader.get_pixbuf: PGdkPixbuf; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_loader_get_pixbuf(@self);
end;

procedure TGdkPixbufLoader.set_size(width: gint; height: gint); cdecl;
begin
  GdkPixbuf2.gdk_pixbuf_loader_set_size(@self, width, height);
end;

function TGdkPixbufLoader.write(buf: Pguint8; count: gsize; error: PPGError): gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_loader_write(@self, buf, count, error);
end;

function TGdkPixbufLoader.write_bytes(buffer: PGBytes; error: PPGError): gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_loader_write_bytes(@self, buffer, error);
end;

function TGdkPixbufSimpleAnim.new(width: gint; height: gint; rate: gfloat): PGdkPixbufSimpleAnim; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_simple_anim_new(width, height, rate);
end;

procedure TGdkPixbufSimpleAnim.add_frame(pixbuf: PGdkPixbuf); cdecl;
begin
  GdkPixbuf2.gdk_pixbuf_simple_anim_add_frame(@self, pixbuf);
end;

function TGdkPixbufSimpleAnim.get_loop: gboolean; cdecl;
begin
  Result := GdkPixbuf2.gdk_pixbuf_simple_anim_get_loop(@self);
end;

procedure TGdkPixbufSimpleAnim.set_loop(loop: gboolean); cdecl;
begin
  GdkPixbuf2.gdk_pixbuf_simple_anim_set_loop(@self, loop);
end;

var
  libgdk_pixbuf_2_0_so_0: TLibHandle;
procedure LoadLibraries;
begin
  libgdk_pixbuf_2_0_so_0 := SafeLoadLibrary('libgdk_pixbuf-2.0.so.0');
end;

procedure LoadProcs;
  procedure LoadProc(var AProc: Pointer; AName: String);
  var
    ProcPtr: Pointer;
  begin
    ProcPtr := GetProcedureAddress(libgdk_pixbuf_2_0_so_0, AName);
    AProc := ProcPtr;
  end;
begin
  LoadProc(Pointer(gdk_pixbuf_add_alpha), 'gdk_pixbuf_add_alpha');
  LoadProc(Pointer(gdk_pixbuf_animation_get_height), 'gdk_pixbuf_animation_get_height');
  LoadProc(Pointer(gdk_pixbuf_animation_get_iter), 'gdk_pixbuf_animation_get_iter');
  LoadProc(Pointer(gdk_pixbuf_animation_get_static_image), 'gdk_pixbuf_animation_get_static_image');
  LoadProc(Pointer(gdk_pixbuf_animation_get_type), 'gdk_pixbuf_animation_get_type');
  LoadProc(Pointer(gdk_pixbuf_animation_get_width), 'gdk_pixbuf_animation_get_width');
  LoadProc(Pointer(gdk_pixbuf_animation_is_static_image), 'gdk_pixbuf_animation_is_static_image');
  LoadProc(Pointer(gdk_pixbuf_animation_iter_advance), 'gdk_pixbuf_animation_iter_advance');
  LoadProc(Pointer(gdk_pixbuf_animation_iter_get_delay_time), 'gdk_pixbuf_animation_iter_get_delay_time');
  LoadProc(Pointer(gdk_pixbuf_animation_iter_get_pixbuf), 'gdk_pixbuf_animation_iter_get_pixbuf');
  LoadProc(Pointer(gdk_pixbuf_animation_iter_get_type), 'gdk_pixbuf_animation_iter_get_type');
  LoadProc(Pointer(gdk_pixbuf_animation_iter_on_currently_loading_frame), 'gdk_pixbuf_animation_iter_on_currently_loading_frame');
  LoadProc(Pointer(gdk_pixbuf_animation_new_from_file), 'gdk_pixbuf_animation_new_from_file');
  LoadProc(Pointer(gdk_pixbuf_animation_new_from_resource), 'gdk_pixbuf_animation_new_from_resource');
  LoadProc(Pointer(gdk_pixbuf_animation_new_from_stream), 'gdk_pixbuf_animation_new_from_stream');
  LoadProc(Pointer(gdk_pixbuf_animation_new_from_stream_async), 'gdk_pixbuf_animation_new_from_stream_async');
  LoadProc(Pointer(gdk_pixbuf_animation_new_from_stream_finish), 'gdk_pixbuf_animation_new_from_stream_finish');
  LoadProc(Pointer(gdk_pixbuf_apply_embedded_orientation), 'gdk_pixbuf_apply_embedded_orientation');
  LoadProc(Pointer(gdk_pixbuf_calculate_rowstride), 'gdk_pixbuf_calculate_rowstride');
  LoadProc(Pointer(gdk_pixbuf_composite), 'gdk_pixbuf_composite');
  LoadProc(Pointer(gdk_pixbuf_composite_color), 'gdk_pixbuf_composite_color');
  LoadProc(Pointer(gdk_pixbuf_composite_color_simple), 'gdk_pixbuf_composite_color_simple');
  LoadProc(Pointer(gdk_pixbuf_copy), 'gdk_pixbuf_copy');
  LoadProc(Pointer(gdk_pixbuf_copy_area), 'gdk_pixbuf_copy_area');
  LoadProc(Pointer(gdk_pixbuf_copy_options), 'gdk_pixbuf_copy_options');
  LoadProc(Pointer(gdk_pixbuf_error_quark), 'gdk_pixbuf_error_quark');
  LoadProc(Pointer(gdk_pixbuf_fill), 'gdk_pixbuf_fill');
  LoadProc(Pointer(gdk_pixbuf_flip), 'gdk_pixbuf_flip');
  LoadProc(Pointer(gdk_pixbuf_format_copy), 'gdk_pixbuf_format_copy');
  LoadProc(Pointer(gdk_pixbuf_format_free), 'gdk_pixbuf_format_free');
  LoadProc(Pointer(gdk_pixbuf_format_get_description), 'gdk_pixbuf_format_get_description');
  LoadProc(Pointer(gdk_pixbuf_format_get_extensions), 'gdk_pixbuf_format_get_extensions');
  LoadProc(Pointer(gdk_pixbuf_format_get_license), 'gdk_pixbuf_format_get_license');
  LoadProc(Pointer(gdk_pixbuf_format_get_mime_types), 'gdk_pixbuf_format_get_mime_types');
  LoadProc(Pointer(gdk_pixbuf_format_get_name), 'gdk_pixbuf_format_get_name');
  LoadProc(Pointer(gdk_pixbuf_format_get_type), 'gdk_pixbuf_format_get_type');
  LoadProc(Pointer(gdk_pixbuf_format_is_disabled), 'gdk_pixbuf_format_is_disabled');
  LoadProc(Pointer(gdk_pixbuf_format_is_save_option_supported), 'gdk_pixbuf_format_is_save_option_supported');
  LoadProc(Pointer(gdk_pixbuf_format_is_scalable), 'gdk_pixbuf_format_is_scalable');
  LoadProc(Pointer(gdk_pixbuf_format_is_writable), 'gdk_pixbuf_format_is_writable');
  LoadProc(Pointer(gdk_pixbuf_format_set_disabled), 'gdk_pixbuf_format_set_disabled');
  LoadProc(Pointer(gdk_pixbuf_get_bits_per_sample), 'gdk_pixbuf_get_bits_per_sample');
  LoadProc(Pointer(gdk_pixbuf_get_byte_length), 'gdk_pixbuf_get_byte_length');
  LoadProc(Pointer(gdk_pixbuf_get_colorspace), 'gdk_pixbuf_get_colorspace');
  LoadProc(Pointer(gdk_pixbuf_get_file_info), 'gdk_pixbuf_get_file_info');
  LoadProc(Pointer(gdk_pixbuf_get_file_info_async), 'gdk_pixbuf_get_file_info_async');
  LoadProc(Pointer(gdk_pixbuf_get_file_info_finish), 'gdk_pixbuf_get_file_info_finish');
  LoadProc(Pointer(gdk_pixbuf_get_formats), 'gdk_pixbuf_get_formats');
  LoadProc(Pointer(gdk_pixbuf_get_has_alpha), 'gdk_pixbuf_get_has_alpha');
  LoadProc(Pointer(gdk_pixbuf_get_height), 'gdk_pixbuf_get_height');
  LoadProc(Pointer(gdk_pixbuf_get_n_channels), 'gdk_pixbuf_get_n_channels');
  LoadProc(Pointer(gdk_pixbuf_get_option), 'gdk_pixbuf_get_option');
  LoadProc(Pointer(gdk_pixbuf_get_options), 'gdk_pixbuf_get_options');
  LoadProc(Pointer(gdk_pixbuf_get_pixels), 'gdk_pixbuf_get_pixels');
  LoadProc(Pointer(gdk_pixbuf_get_pixels_with_length), 'gdk_pixbuf_get_pixels_with_length');
  LoadProc(Pointer(gdk_pixbuf_get_rowstride), 'gdk_pixbuf_get_rowstride');
  LoadProc(Pointer(gdk_pixbuf_get_type), 'gdk_pixbuf_get_type');
  LoadProc(Pointer(gdk_pixbuf_get_width), 'gdk_pixbuf_get_width');
  LoadProc(Pointer(gdk_pixbuf_loader_close), 'gdk_pixbuf_loader_close');
  LoadProc(Pointer(gdk_pixbuf_loader_get_animation), 'gdk_pixbuf_loader_get_animation');
  LoadProc(Pointer(gdk_pixbuf_loader_get_format), 'gdk_pixbuf_loader_get_format');
  LoadProc(Pointer(gdk_pixbuf_loader_get_pixbuf), 'gdk_pixbuf_loader_get_pixbuf');
  LoadProc(Pointer(gdk_pixbuf_loader_get_type), 'gdk_pixbuf_loader_get_type');
  LoadProc(Pointer(gdk_pixbuf_loader_new), 'gdk_pixbuf_loader_new');
  LoadProc(Pointer(gdk_pixbuf_loader_new_with_mime_type), 'gdk_pixbuf_loader_new_with_mime_type');
  LoadProc(Pointer(gdk_pixbuf_loader_new_with_type), 'gdk_pixbuf_loader_new_with_type');
  LoadProc(Pointer(gdk_pixbuf_loader_set_size), 'gdk_pixbuf_loader_set_size');
  LoadProc(Pointer(gdk_pixbuf_loader_write), 'gdk_pixbuf_loader_write');
  LoadProc(Pointer(gdk_pixbuf_loader_write_bytes), 'gdk_pixbuf_loader_write_bytes');
  LoadProc(Pointer(gdk_pixbuf_new), 'gdk_pixbuf_new');
  LoadProc(Pointer(gdk_pixbuf_new_from_bytes), 'gdk_pixbuf_new_from_bytes');
  LoadProc(Pointer(gdk_pixbuf_new_from_data), 'gdk_pixbuf_new_from_data');
  LoadProc(Pointer(gdk_pixbuf_new_from_file), 'gdk_pixbuf_new_from_file');
  LoadProc(Pointer(gdk_pixbuf_new_from_file_at_scale), 'gdk_pixbuf_new_from_file_at_scale');
  LoadProc(Pointer(gdk_pixbuf_new_from_file_at_size), 'gdk_pixbuf_new_from_file_at_size');
  LoadProc(Pointer(gdk_pixbuf_new_from_resource), 'gdk_pixbuf_new_from_resource');
  LoadProc(Pointer(gdk_pixbuf_new_from_resource_at_scale), 'gdk_pixbuf_new_from_resource_at_scale');
  LoadProc(Pointer(gdk_pixbuf_new_from_stream), 'gdk_pixbuf_new_from_stream');
  LoadProc(Pointer(gdk_pixbuf_new_from_stream_async), 'gdk_pixbuf_new_from_stream_async');
  LoadProc(Pointer(gdk_pixbuf_new_from_stream_at_scale), 'gdk_pixbuf_new_from_stream_at_scale');
  LoadProc(Pointer(gdk_pixbuf_new_from_stream_at_scale_async), 'gdk_pixbuf_new_from_stream_at_scale_async');
  LoadProc(Pointer(gdk_pixbuf_new_from_stream_finish), 'gdk_pixbuf_new_from_stream_finish');
  LoadProc(Pointer(gdk_pixbuf_new_from_xpm_data), 'gdk_pixbuf_new_from_xpm_data');
  LoadProc(Pointer(gdk_pixbuf_new_subpixbuf), 'gdk_pixbuf_new_subpixbuf');
  LoadProc(Pointer(gdk_pixbuf_read_pixel_bytes), 'gdk_pixbuf_read_pixel_bytes');
  LoadProc(Pointer(gdk_pixbuf_read_pixels), 'gdk_pixbuf_read_pixels');
  LoadProc(Pointer(gdk_pixbuf_remove_option), 'gdk_pixbuf_remove_option');
  LoadProc(Pointer(gdk_pixbuf_rotate_simple), 'gdk_pixbuf_rotate_simple');
  LoadProc(Pointer(gdk_pixbuf_saturate_and_pixelate), 'gdk_pixbuf_saturate_and_pixelate');
  LoadProc(Pointer(gdk_pixbuf_save), 'gdk_pixbuf_save');
  LoadProc(Pointer(gdk_pixbuf_save_to_buffer), 'gdk_pixbuf_save_to_buffer');
  LoadProc(Pointer(gdk_pixbuf_save_to_bufferv), 'gdk_pixbuf_save_to_bufferv');
  LoadProc(Pointer(gdk_pixbuf_save_to_callback), 'gdk_pixbuf_save_to_callback');
  LoadProc(Pointer(gdk_pixbuf_save_to_callbackv), 'gdk_pixbuf_save_to_callbackv');
  LoadProc(Pointer(gdk_pixbuf_save_to_stream), 'gdk_pixbuf_save_to_stream');
  LoadProc(Pointer(gdk_pixbuf_save_to_stream_async), 'gdk_pixbuf_save_to_stream_async');
  LoadProc(Pointer(gdk_pixbuf_save_to_stream_finish), 'gdk_pixbuf_save_to_stream_finish');
  LoadProc(Pointer(gdk_pixbuf_save_to_streamv), 'gdk_pixbuf_save_to_streamv');
  LoadProc(Pointer(gdk_pixbuf_save_to_streamv_async), 'gdk_pixbuf_save_to_streamv_async');
  LoadProc(Pointer(gdk_pixbuf_savev), 'gdk_pixbuf_savev');
  LoadProc(Pointer(gdk_pixbuf_scale), 'gdk_pixbuf_scale');
  LoadProc(Pointer(gdk_pixbuf_scale_simple), 'gdk_pixbuf_scale_simple');
  LoadProc(Pointer(gdk_pixbuf_set_option), 'gdk_pixbuf_set_option');
  LoadProc(Pointer(gdk_pixbuf_simple_anim_add_frame), 'gdk_pixbuf_simple_anim_add_frame');
  LoadProc(Pointer(gdk_pixbuf_simple_anim_get_loop), 'gdk_pixbuf_simple_anim_get_loop');
  LoadProc(Pointer(gdk_pixbuf_simple_anim_get_type), 'gdk_pixbuf_simple_anim_get_type');
  LoadProc(Pointer(gdk_pixbuf_simple_anim_iter_get_type), 'gdk_pixbuf_simple_anim_iter_get_type');
  LoadProc(Pointer(gdk_pixbuf_simple_anim_new), 'gdk_pixbuf_simple_anim_new');
  LoadProc(Pointer(gdk_pixbuf_simple_anim_set_loop), 'gdk_pixbuf_simple_anim_set_loop');
end;

procedure UnloadLibraries;
begin
 if libgdk_pixbuf_2_0_so_0 <> 0 then
   UnloadLibrary(libgdk_pixbuf_2_0_so_0);
   libgdk_pixbuf_2_0_so_0 := 0;
  gdk_pixbuf_add_alpha := nil;
  gdk_pixbuf_animation_get_height := nil;
  gdk_pixbuf_animation_get_iter := nil;
  gdk_pixbuf_animation_get_static_image := nil;
  gdk_pixbuf_animation_get_type := nil;
  gdk_pixbuf_animation_get_width := nil;
  gdk_pixbuf_animation_is_static_image := nil;
  gdk_pixbuf_animation_iter_advance := nil;
  gdk_pixbuf_animation_iter_get_delay_time := nil;
  gdk_pixbuf_animation_iter_get_pixbuf := nil;
  gdk_pixbuf_animation_iter_get_type := nil;
  gdk_pixbuf_animation_iter_on_currently_loading_frame := nil;
  gdk_pixbuf_animation_new_from_file := nil;
  gdk_pixbuf_animation_new_from_resource := nil;
  gdk_pixbuf_animation_new_from_stream := nil;
  gdk_pixbuf_animation_new_from_stream_async := nil;
  gdk_pixbuf_animation_new_from_stream_finish := nil;
  gdk_pixbuf_apply_embedded_orientation := nil;
  gdk_pixbuf_calculate_rowstride := nil;
  gdk_pixbuf_composite := nil;
  gdk_pixbuf_composite_color := nil;
  gdk_pixbuf_composite_color_simple := nil;
  gdk_pixbuf_copy := nil;
  gdk_pixbuf_copy_area := nil;
  gdk_pixbuf_copy_options := nil;
  gdk_pixbuf_error_quark := nil;
  gdk_pixbuf_fill := nil;
  gdk_pixbuf_flip := nil;
  gdk_pixbuf_format_copy := nil;
  gdk_pixbuf_format_free := nil;
  gdk_pixbuf_format_get_description := nil;
  gdk_pixbuf_format_get_extensions := nil;
  gdk_pixbuf_format_get_license := nil;
  gdk_pixbuf_format_get_mime_types := nil;
  gdk_pixbuf_format_get_name := nil;
  gdk_pixbuf_format_get_type := nil;
  gdk_pixbuf_format_is_disabled := nil;
  gdk_pixbuf_format_is_save_option_supported := nil;
  gdk_pixbuf_format_is_scalable := nil;
  gdk_pixbuf_format_is_writable := nil;
  gdk_pixbuf_format_set_disabled := nil;
  gdk_pixbuf_get_bits_per_sample := nil;
  gdk_pixbuf_get_byte_length := nil;
  gdk_pixbuf_get_colorspace := nil;
  gdk_pixbuf_get_file_info := nil;
  gdk_pixbuf_get_file_info_async := nil;
  gdk_pixbuf_get_file_info_finish := nil;
  gdk_pixbuf_get_formats := nil;
  gdk_pixbuf_get_has_alpha := nil;
  gdk_pixbuf_get_height := nil;
  gdk_pixbuf_get_n_channels := nil;
  gdk_pixbuf_get_option := nil;
  gdk_pixbuf_get_options := nil;
  gdk_pixbuf_get_pixels := nil;
  gdk_pixbuf_get_pixels_with_length := nil;
  gdk_pixbuf_get_rowstride := nil;
  gdk_pixbuf_get_type := nil;
  gdk_pixbuf_get_width := nil;
  gdk_pixbuf_loader_close := nil;
  gdk_pixbuf_loader_get_animation := nil;
  gdk_pixbuf_loader_get_format := nil;
  gdk_pixbuf_loader_get_pixbuf := nil;
  gdk_pixbuf_loader_get_type := nil;
  gdk_pixbuf_loader_new := nil;
  gdk_pixbuf_loader_new_with_mime_type := nil;
  gdk_pixbuf_loader_new_with_type := nil;
  gdk_pixbuf_loader_set_size := nil;
  gdk_pixbuf_loader_write := nil;
  gdk_pixbuf_loader_write_bytes := nil;
  gdk_pixbuf_new := nil;
  gdk_pixbuf_new_from_bytes := nil;
  gdk_pixbuf_new_from_data := nil;
  gdk_pixbuf_new_from_file := nil;
  gdk_pixbuf_new_from_file_at_scale := nil;
  gdk_pixbuf_new_from_file_at_size := nil;
  gdk_pixbuf_new_from_resource := nil;
  gdk_pixbuf_new_from_resource_at_scale := nil;
  gdk_pixbuf_new_from_stream := nil;
  gdk_pixbuf_new_from_stream_async := nil;
  gdk_pixbuf_new_from_stream_at_scale := nil;
  gdk_pixbuf_new_from_stream_at_scale_async := nil;
  gdk_pixbuf_new_from_stream_finish := nil;
  gdk_pixbuf_new_from_xpm_data := nil;
  gdk_pixbuf_new_subpixbuf := nil;
  gdk_pixbuf_read_pixel_bytes := nil;
  gdk_pixbuf_read_pixels := nil;
  gdk_pixbuf_remove_option := nil;
  gdk_pixbuf_rotate_simple := nil;
  gdk_pixbuf_saturate_and_pixelate := nil;
  gdk_pixbuf_save := nil;
  gdk_pixbuf_save_to_buffer := nil;
  gdk_pixbuf_save_to_bufferv := nil;
  gdk_pixbuf_save_to_callback := nil;
  gdk_pixbuf_save_to_callbackv := nil;
  gdk_pixbuf_save_to_stream := nil;
  gdk_pixbuf_save_to_stream_async := nil;
  gdk_pixbuf_save_to_stream_finish := nil;
  gdk_pixbuf_save_to_streamv := nil;
  gdk_pixbuf_save_to_streamv_async := nil;
  gdk_pixbuf_savev := nil;
  gdk_pixbuf_scale := nil;
  gdk_pixbuf_scale_simple := nil;
  gdk_pixbuf_set_option := nil;
  gdk_pixbuf_simple_anim_add_frame := nil;
  gdk_pixbuf_simple_anim_get_loop := nil;
  gdk_pixbuf_simple_anim_get_type := nil;
  gdk_pixbuf_simple_anim_iter_get_type := nil;
  gdk_pixbuf_simple_anim_new := nil;
  gdk_pixbuf_simple_anim_set_loop := nil;
end;

initialization
LoadLibraries;
LoadProcs;

finalization
UnloadLibraries;

end.